### ISSUE TITLE
Can't stop the execution programmatically

### ISSUE THREAD

**Issue by Calcifer1001** [pyth-network/pyth-client-js#28]
After calling the start method, the execution starts perfectly and after calling stop, stops logging, but the execution doesn't stop and the program keeps doing something. Since stop only clears the callback array, probably the start method keeps running, and the for loops don't do anything, but still runs, so the program never finishes.

Thanks

**Comment by ali-bahjati** [comment]
It is because solana doesn't provide any way of closing their websocket or unsubscribing..
