### ISSUE TITLE
Add more granular price fetching

### ISSUE THREAD

**Issue by cryptopapi997** [pyth-network/pyth-client-js#60]
Thanks for the great SDK guys!
One request, though: It is currently only possible to fetch and listen to every single price feed at once and parse afterwards. This differs from the rust SDK where we can listen to individual price feeds, which is far more useful, as it significantly reduces parsing overhead for the client. Adding functionality to fetch / listen to individual price feeds would be a great improvement imo. I've found `parsePriceData` to parse individual accounts, but am wondering if this is recommended to use like that.

**Comment by jayantk** [comment]
Hey thank you for the suggestion. Fetching/listening to individual feeds is definitely possible, though it isn't high on our priority list at the moment. We would definitely accept a community PR to implement that functionality though.

I think the PR would be pretty straightforward -- all you have to do is query for single solana accounts (using their api) and then call parsePriceData on the result.

**Comment by cryptopapi997** [comment]
Sounds good, just created a PR https://github.com/pyth-network/pyth-client-js/pull/61

**Comment by jayantk** [comment]
Resolved by https://github.com/pyth-network/pyth-client-js/pull/61
